version: '4.2'
services:
  zookeeper:
    image: zookeeper:3.9.1-jre-17
    hostname: zookeeper
    ports: [ "2181:2181" ]
    #environment:
     # ZOO_MY_ID: 1
      #ZOO_PORT: 2181
      #ZOO_SERVERS: "server.1=zookeeper:2888:3888"
    volumes:
     - ./data1/zookeeper/data:/data
     - ./data1/zookeeper/datalog:/datalog
    restart: unless-stopped
  broker1:
    image: confluentinc/cp-kafka:7.5.1
    hostname: broker1
    ports:
    - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://broker1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
    volumes:
      - ./data1/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
    restart: unless-stopped